const DATA_KEY = "customers";
const META_KEY = "meta";
const CUSTOMER_PREFIX = "customer:";

const ADMIN_PAGE = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cellix — Customer Balance</title>
<script src="https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js"></script>
<style>body{font-family:Arial,sans-serif;background:#f4f7fb;margin:0;padding:20px;color:#172033}.card{max-width:900px;margin:auto;background:#fff;border-radius:22px;padding:24px;box-shadow:0 10px 35px #0001}h1{color:#1677ff;margin:0 0 8px}input,button{width:100%;height:50px;border-radius:12px;border:1px solid #d5dce7;padding:0 14px;font-size:15px;box-sizing:border-box;margin-top:10px}button{background:#1677ff;color:#fff;border:0;font-weight:800}#msg{margin-top:15px;font-weight:700;white-space:pre-wrap}.ok{color:#16803c}.err{color:#c62828}.list{margin-top:25px}.customer{padding:14px 0;border-bottom:1px solid #eee}.link{word-break:break-all;color:#1677ff}.wa{display:inline-block;margin-top:8px;background:#159447;color:#fff;text-decoration:none;padding:9px 12px;border-radius:9px}</style></head>
<body><div class="card"><h1>Cellix</h1><h2>Customer Balance</h2><p>Upload the latest Excel report.</p><input id="token" type="password" placeholder="Admin token"><input id="file" type="file" accept=".xlsx,.xls,.csv"><button id="upload">Upload Excel</button><div id="msg"></div><div id="list" class="list"></div></div>
<script>
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=n=>new Intl.NumberFormat('en-US').format(Number(n)||0)+' LBP';
function show(t,ok=false){$('msg').textContent=t;$('msg').className=ok?'ok':'err'}
function waPhone(v){let d=String(v??'').replace(/\\D/g,'');if(d.startsWith('0'))d='961'+d.slice(1);else if(!d.startsWith('961'))d='961'+d;return d}
function render(cs){$('list').innerHTML='<h3>Private Links</h3>'+cs.map(c=>{const link=location.origin+'/c/'+encodeURIComponent(c.token);const text='إدارة Cellix تشكركم على ثقتكم بنا،\\n\\nونشارككم رابطكم الخاص للاطلاع على رصيدكم الحالي:\\n\\nالرابط:\\n'+link+'\\n\\nنرجو منكم عدم مشاركة هذا الرابط مع أي شخص، حفاظاً على خصوصية معلومات حسابكم.\\n\\nكما نوصي بحفظ الرابط على هاتفكم من خلال تثبيت صفحة Cellix، وذلك باتباع الخطوات التالية:\\n\\n1- افتحوا الرابط باستخدام Google Chrome.\\n2- اضغطوا على ⋮ ثم اختاروا Install / تثبيت التطبيق إذا ظهر الخيار.\\n3- اضغطوا Install / تثبيت للتأكيد.\\n\\nلمزيد من التفاصيل أو المساعدة، يرجى التواصل مع إدارة Cellix حصراً على الرقم الخاص: 81024686';return '<div class="customer"><b>'+esc(c.name)+'</b><br>Balance: '+money(c.remaining)+'<br><span class="link">'+esc(link)+'</span><br><a class="wa" target="_blank" href="https://wa.me/'+waPhone(c.phone)+'?text='+encodeURIComponent(text)+'">WhatsApp</a></div>'}).join('')}
$('upload').onclick=async()=>{try{const token=$('token').value.trim(),f=$('file').files[0];if(!token)throw Error('Enter admin token.');if(!f)throw Error('Select Excel file.');show('Reading Excel...',true);const b=await f.arrayBuffer();const wb=XLSX.read(b,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});if(!rows.length)throw Error('Excel is empty.');const h=rows[0].map(x=>String(x).trim().toLowerCase());const find=(...a)=>a.map(x=>h.indexOf(x)).find(i=>i>=0);const ni=find('name','client name','customer name'),pi=find('contact number','phone','phone number','contact'),ri=find('remaining balance','remaining','balance due','amount due');if(ni==null||pi==null||ri==null)throw Error('Required columns: Name, Contact Number, Remaining Balance.');const clients=rows.slice(1).map(r=>({name:String(r[ni]??'').trim(),phone:String(r[pi]??'').trim(),remaining:Number(String(r[ri]??0).replace(/,/g,'').replace(/[^0-9.-]/g,''))||0})).filter(c=>c.name||c.phone);if(!clients.length)throw Error('No customers found.');const res=await fetch('/api/upload',{method:'POST',headers:{'content-type':'application/json','x-admin-token':token},body:JSON.stringify({clients})});const text=await res.text();let d;try{d=JSON.parse(text)}catch{throw Error('Server returned an unexpected response. Please try again.')}if(!res.ok||!d.ok)throw Error(d.error||'Upload failed.');show('✓ '+d.count+' customers updated. Private links preserved.',true);render(d.customers)}catch(e){show('Upload failed: '+e.message)}};
</script></body></html>`;

function customerHtml(c){const checkedAt=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Beirut',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())+' • Lebanon Time (UTC+3)';const amount=Number(c.remaining)||0;const paid=amount===0;const safeName=String(c.name??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cellix — Your Balance</title><style>body{margin:0;background:#f4f7fb;font-family:Arial,sans-serif;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px;color:#172033}.card{width:min(430px,100%);background:#fff;border-radius:25px;padding:28px;text-align:center;box-shadow:0 12px 40px #0001}.logo{font-size:42px;font-weight:900;color:#1677ff}.sub{color:#687386;margin:8px 0 28px}.name{font-size:20px;font-weight:800}.label{color:#687386;margin-top:24px}.amount{font-size:36px;font-weight:900;margin:8px 0 15px}.status{display:inline-block;padding:9px 15px;border-radius:999px;font-weight:800}.paid{background:#e9f8ef;color:#16803c}.out{background:#fff4df;color:#9a6500}.time{font-size:12px;color:#8b95a5;margin-top:22px}</style></head><body><main class="card"><div class="logo">Cellix</div><div class="sub">Your outstanding balance</div><div class="name">${safeName}</div><div class="label">Remaining balance</div><div class="amount">${new Intl.NumberFormat('en-US').format(amount)} LBP</div><div><span class="status ${paid?'paid':'out'}">${paid?'✓ Account Paid':'Outstanding Balance'}</span></div><div class="time">Checked at: ${checkedAt}</div></main></body></html>`}
function notFoundHtml(){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cellix</title><style>body{margin:0;background:#f4f7fb;font-family:Arial,sans-serif;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px}.card{width:min(430px,100%);background:#fff;border-radius:25px;padding:28px;text-align:center}.logo{font-size:42px;font-weight:900;color:#1677ff}</style></head><body><main class="card"><div class="logo">Cellix</div><p>Private link not found.</p></main></body></html>`}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store'}})}
function html(s,status=200){return new Response(s,{status,headers:{'content-type':'text/html;charset=UTF-8','cache-control':'no-store'}})}
function normPhone(v){return String(v??'').replace(/\D/g,'')}
function makeToken(){return crypto.randomUUID().replace(/-/g,'')+crypto.randomUUID().replace(/-/g,'')}

export default {async fetch(request,env){const url=new URL(request.url);
if(url.pathname==='/admin/upload')return html(ADMIN_PAGE);
if(url.pathname.startsWith('/c/')){const token=decodeURIComponent(url.pathname.slice(3));if(!token)return html(notFoundHtml(),404);let c=null;const direct=await env.BALANCES.get(CUSTOMER_PREFIX+token,'json');if(direct)c=direct;if(!c){const raw=await env.BALANCES.get(DATA_KEY);if(raw)try{const cs=JSON.parse(raw);c=cs.find(x=>x.token===token)||null;if(c)await env.BALANCES.put(CUSTOMER_PREFIX+token,JSON.stringify(c));}catch{}}return c?html(customerHtml(c)):html(notFoundHtml(),404)}
if(url.pathname==='/api/private/'||url.pathname.startsWith('/api/private/')){const token=decodeURIComponent(url.pathname.slice('/api/private/'.length));const c=await env.BALANCES.get(CUSTOMER_PREFIX+token,'json');return c?json({ok:true,customer:c}):json({ok:false,error:'Private link not found.'},404)}
if(url.pathname==='/api/upload'&&request.method==='POST'){if(request.headers.get('x-admin-token')!==env.ADMIN_TEST_TOKEN)return json({ok:false,error:'Unauthorized'},401);let body;try{body=await request.json()}catch{return json({ok:false,error:'Invalid JSON'},400)}if(!Array.isArray(body.clients)||!body.clients.length)return json({ok:false,error:'No customers received.'},400);let old=[];const raw=await env.BALANCES.get(DATA_KEY);if(raw)try{old=JSON.parse(raw)}catch{}const oldMap=new Map(old.filter(c=>c&&c.phone).map(c=>[normPhone(c.phone),c]));const incoming=new Map(body.clients.filter(c=>c&&c.phone).map(c=>[normPhone(c.phone),c]));for(const c of old){if(!c.token)c.token=makeToken();const n=incoming.get(normPhone(c.phone));if(n){c.name=n.name;c.phone=n.phone;c.remaining=Number(n.remaining)||0}else{c.remaining=0}await env.BALANCES.put(CUSTOMER_PREFIX+c.token,JSON.stringify(c))}for(const n of body.clients){const p=normPhone(n.phone);if(!p||oldMap.has(p))continue;const c={name:n.name,phone:n.phone,remaining:Number(n.remaining)||0,token:makeToken()};old.push(c);oldMap.set(p,c);await env.BALANCES.put(CUSTOMER_PREFIX+c.token,JSON.stringify(c))}await env.BALANCES.put(DATA_KEY,JSON.stringify(old));await env.BALANCES.put(META_KEY,JSON.stringify({updatedAt:new Date().toISOString(),count:old.length}));return json({ok:true,count:body.clients.length,customers:old.map(c=>({name:c.name,phone:c.phone,remaining:c.remaining,token:c.token}))})}
return Response.redirect(new URL('/admin/upload',request.url).toString(),302)}};
