const DATA_KEY = "customers";
const META_KEY = "meta";
const CUSTOMER_PREFIX = "customer:";
const EXCHANGE_KEY = "exchange_rate";
const DEFAULT_EXCHANGE_RATE = 89500;

const ADMIN_PAGE = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cellix — Customer Balance</title>

<style>body{font-family:Arial,sans-serif;background:#f4f7fb;margin:0;padding:20px;color:#172033}.card{max-width:900px;margin:auto;background:#fff;border-radius:22px;padding:24px;box-shadow:0 10px 35px #0001}h1{color:#1677ff;margin:0 0 8px}.rate{background:#eef6ff;border-radius:16px;padding:16px;margin:18px 0 24px}.rate-title{font-weight:800;font-size:17px}.rate-row{display:flex;gap:10px;align-items:center}.rate-row input{flex:1}.rate-row button{width:130px}.hint{font-size:13px;color:#687386;margin-top:7px}input,button{width:100%;height:50px;border-radius:12px;border:1px solid #d5dce7;padding:0 14px;font-size:15px;box-sizing:border-box;margin-top:10px}button{background:#1677ff;color:#fff;border:0;font-weight:800}.rate-row input,.rate-row button{margin-top:10px}#msg{margin-top:15px;font-weight:700;white-space:pre-wrap}.ok{color:#16803c}.err{color:#c62828}.list{margin-top:25px}.customer{padding:14px 0;border-bottom:1px solid #eee}.link{display:inline-block;word-break:break-all;color:#1677ff;text-decoration:none}.wa{display:inline-block;margin-top:8px;background:#159447;color:#fff;text-decoration:none;padding:9px 12px;border-radius:9px}</style></head>
<body><div class="card"><h1>Cellix</h1><div class="rate"><div class="rate-title">Exchange Rate (1 USD)</div><div class="rate-row"><input id="rate" type="number" min="1" step="1" placeholder="89500"><button id="saveRate">Save</button></div><div class="hint">Set how many LBP equal 1 USD. This rate is used only to calculate the USD amount shown to customers.</div></div><h2>Customer Balance</h2><p>Upload the latest Excel report.</p><input id="token" type="password" placeholder="Admin token"><input id="file" type="file" accept=".xlsx,.csv"><button id="upload">Upload Excel</button><div id="msg"></div><div id="list" class="list"></div></div>
<script>
async function readExcelFile(file){
  const buf=await file.arrayBuffer();
  if(/\.csv$/i.test(file.name)){const text=new TextDecoder().decode(buf);return parseCsv(text)}
  return parseXlsx(buf);
}
function parseCsv(text){
  const rows=[];let row=[],cell='',q=false;
  for(let i=0;i<text.length;i++){const ch=text[i],nx=text[i+1];if(q){if(ch==='"'&&nx==='"'){cell+='"';i++}else if(ch==='"')q=false;else cell+=ch}else{if(ch==='"')q=true;else if(ch===','){row.push(cell);cell=''}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=ch}}
  if(cell!==''||row.length){row.push(cell.replace(/\r$/,''));rows.push(row)}return rows.filter(r=>r.some(v=>String(v).trim()!==''));
}
async function parseXlsx(buf){
  const files=await unzipEntries(buf);
  const text=async name=>{const b=files.get(name);if(!b)throw new Error('Missing '+name);return new TextDecoder().decode(b)};
  const workbook=new DOMParser().parseFromString(await text('xl/workbook.xml'),'application/xml');
  const first=workbook.querySelector('sheet');
  if(!first)throw new Error('Excel workbook has no sheets.');
  const relId=first.getAttribute('r:id');
  const relDoc=new DOMParser().parseFromString(await text('xl/_rels/workbook.xml.rels'),'application/xml');
  let rel=null;for(const r of relDoc.getElementsByTagName('Relationship'))if(r.getAttribute('Id')===relId){rel=r;break}
  if(!rel)throw new Error('Could not locate the first Excel sheet.');
  let target=rel.getAttribute('Target')||'';target=target.replace(/^\//,'');if(target.startsWith('xl/')){}else target='xl/'+target.replace(/^\.\//,'');
  const sheetXml=await text(target);
  const shared=files.has('xl/sharedStrings.xml')?parseSharedStrings(await text('xl/sharedStrings.xml')):[];
  return parseSheet(sheetXml,shared);
}
function parseSharedStrings(xml){const d=new DOMParser().parseFromString(xml,'application/xml');return Array.from(d.getElementsByTagName('si')).map(si=>Array.from(si.getElementsByTagName('t')).map(t=>t.textContent||'').join(''))}
function parseSheet(xml,shared){
  const d=new DOMParser().parseFromString(xml,'application/xml');const rows=[];for(const rowEl of d.getElementsByTagName('row')){const row=[];for(const c of rowEl.children){if(c.tagName!=='c')continue;const ref=c.getAttribute('r')||'';const m=/([A-Z]+)\d+/.exec(ref);if(!m)continue;let col=0;for(const ch of m[1])col=col*26+ch.charCodeAt(0)-64;col--;while(row.length<col)row.push('');const type=c.getAttribute('t')||'';const v=c.getElementsByTagName('v')[0];const is=c.getElementsByTagName('is')[0];let value='';if(type==='s'&&v)value=shared[Number(v.textContent)]??'';else if(type==='inlineStr'&&is)value=Array.from(is.getElementsByTagName('t')).map(t=>t.textContent||'').join('');else if(v)value=v.textContent||'';row[col]=value}rows.push(row)}return rows}
async function unzipEntries(buf){
  const u=new Uint8Array(buf),dv=new DataView(buf);let eocd=-1;for(let i=u.length-22;i>=Math.max(0,u.length-65558);i--){if(dv.getUint32(i,false)===0x06054b50){eocd=i;break}}if(eocd<0)throw new Error('Invalid XLSX file.');
  const count=dv.getUint16(eocd+10,true),cdSize=dv.getUint32(eocd+12,true),cdOffset=dv.getUint32(eocd+16,true);let p=cdOffset;const out=new Map();
  for(let n=0;n<count;n++){if(dv.getUint32(p,false)!==0x02014b50)throw new Error('Invalid XLSX archive.');const method=dv.getUint16(p+10,true),csize=dv.getUint32(p+20,true),usize=dv.getUint32(p+24,true),nl=dv.getUint16(p+28,true),xl=dv.getUint16(p+30,true),cl=dv.getUint16(p+32,true),local=dv.getUint32(p+42,true);const name=new TextDecoder().decode(u.slice(p+46,p+46+nl));const lp=local;if(dv.getUint32(lp,false)!==0x04034b50)throw new Error('Invalid XLSX entry.');const lnl=dv.getUint16(lp+26,true),lxl=dv.getUint16(lp+28,true);const data=u.slice(lp+30+lnl+lxl,lp+30+lnl+lxl+csize);let bytes;if(method===0)bytes=data;else if(method===8){const ds=new DecompressionStream('deflate-raw');bytes=new Uint8Array(await new Response(new Blob([data]).stream().pipeThrough(ds)).arrayBuffer())}else throw new Error('Unsupported XLSX compression.');if(usize&&bytes.length!==usize){}out.set(name,bytes);p+=46+nl+xl+cl}return out;
}
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(t,ok=false){$('msg').textContent=t;$('msg').className=ok?'ok':'err'}
function waPhone(v){let d=String(v??'').replace(/\D/g,'');if(d.startsWith('0'))d='961'+d.slice(1);else if(!d.startsWith('961'))d='961'+d;return d}
function render(cs){$('list').innerHTML='<h3>Private Links</h3>'+cs.map(c=>{const link=location.origin+'/c/'+encodeURIComponent(c.token);const text='إدارة Cellix تشكركم على ثقتكم بنا،\n\nونشارككم رابطكم الخاص للاطلاع على رصيدكم الحالي:\n\nالرابط:\n'+link+'\n\nنرجو منكم عدم مشاركة هذا الرابط مع أي شخص، حفاظاً على خصوصية معلومات حسابكم.\n\nكما نوصي بحفظ الرابط على هاتفكم من خلال تثبيت صفحة Cellix، وذلك باتباع الخطوات التالية:\n\n1- افتحوا الرابط باستخدام Google Chrome.\n2- اضغطوا على ⋮ ثم اختاروا Install / تثبيت التطبيق إذا ظهر الخيار.\n3- اضغطوا Install / تثبيت للتأكيد.\n\nلمزيد من التفاصيل أو المساعدة، يرجى التواصل مع إدارة Cellix حصراً على الرقم الخاص: 81024686';return '<div class="customer"><b>'+esc(c.name)+'</b><br><a class="link" target="_blank" rel="noopener" href="'+esc(link)+'">'+esc(link)+'</a><br><a class="wa" target="_blank" rel="noopener" href="https://wa.me/'+waPhone(c.phone)+'?text='+encodeURIComponent(text)+'">WhatsApp</a></div>'}).join('')}
(async()=>{try{const r=await fetch('/api/rate');const d=await r.json();$('rate').value=d.rate}catch{}})();
$('saveRate').onclick=async()=>{try{const token=$('token').value.trim(),rate=Number($('rate').value);if(!token)throw Error('Enter admin token first.');if(!Number.isFinite(rate)||rate<=0)throw Error('Enter a valid exchange rate.');const res=await fetch('/api/rate',{method:'POST',headers:{'content-type':'application/json','x-admin-token':token},body:JSON.stringify({rate})});const d=await res.json();if(!res.ok||!d.ok)throw Error(d.error||'Could not save exchange rate.');show('✓ Exchange rate saved.',true)}catch(e){show('Rate update failed: '+e.message)}};
$('upload').onclick=async()=>{try{const token=$('token').value.trim(),f=$('file').files[0];if(!token)throw Error('Enter admin token.');if(!f)throw Error('Select Excel file.');show('Reading Excel...',true);const rows=await readExcelFile(f);if(!rows.length)throw Error('Excel is empty.');const h=rows[0].map(x=>String(x).trim().toLowerCase());const find=(...a)=>a.map(x=>h.indexOf(x)).find(i=>i>=0);const ni=find('name','client name','customer name'),pi=find('contact number','phone','phone number','contact'),ri=find('remaining balance','remaining','balance due','amount due');if(ni==null||pi==null||ri==null)throw Error('Required columns: Name, Contact Number, Remaining Balance.');const clients=rows.slice(1).map(r=>({name:String(r[ni]??'').trim(),phone:String(r[pi]??'').trim(),remaining:Number(String(r[ri]??0).replace(/,/g,'').replace(/[^0-9.-]/g,''))||0})).filter(c=>c.name||c.phone);if(!clients.length)throw Error('No customers found.');const res=await fetch('/api/upload',{method:'POST',headers:{'content-type':'application/json','x-admin-token':token},body:JSON.stringify({clients})});const text=await res.text();let d;try{d=JSON.parse(text)}catch{throw Error('Server returned an unexpected response. Please try again.')}if(!res.ok||!d.ok)throw Error(d.error||'Upload failed.');show('✓ '+d.count+' customers updated. Private links preserved.',true);render(d.customers)}catch(e){show('Upload failed: '+e.message)}};
</script></body></html>`;

function customerHtml(c,exchangeRate){const checkedAt=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Beirut',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())+' • Lebanon Time (UTC+3)';const amount=Number(c.remaining)||0;const rate=Number(exchangeRate)||DEFAULT_EXCHANGE_RATE;const usd=amount/rate;const paid=amount===0;const safeName=String(c.name??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cellix — Your Balance</title><style>body{margin:0;background:#f4f7fb;font-family:Arial,sans-serif;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px;color:#172033}.card{width:min(430px,100%);background:#fff;border-radius:25px;padding:28px;text-align:center;box-shadow:0 12px 40px #0001}.logo{font-size:42px;font-weight:900;color:#1677ff}.sub{color:#687386;margin:8px 0 28px}.name{font-size:20px;font-weight:800}.label{color:#687386;margin-top:24px}.amount{font-size:36px;font-weight:900;margin:8px 0 4px}.usd{font-size:24px;font-weight:800;color:#1677ff;margin-bottom:15px}.status{display:inline-block;padding:9px 15px;border-radius:999px;font-weight:800}.paid{background:#e9f8ef;color:#16803c}.out{background:#fff4df;color:#9a6500}.time{font-size:12px;color:#8b95a5;margin-top:22px}</style></head><body><main class="card"><div class="logo">Cellix</div><div class="sub">Your outstanding balance</div><div class="name">${safeName}</div><div class="label">Remaining balance</div><div class="amount">${new Intl.NumberFormat('en-US').format(amount)} LBP</div><div class="usd">≈ $${usd.toFixed(2)} USD</div><div><span class="status ${paid?'paid':'out'}">${paid?'✓ Account Paid':'Outstanding Balance'}</span></div><div class="time">Checked at: ${checkedAt}</div></main></body></html>`}

function notFoundHtml(){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cellix</title><style>body{margin:0;background:#f4f7fb;font-family:Arial,sans-serif;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px}.card{width:min(430px,100%);background:#fff;border-radius:25px;padding:28px;text-align:center}.logo{font-size:42px;font-weight:900;color:#1677ff}</style></head><body><main class="card"><div class="logo">Cellix</div><p>Private link not found.</p></main></body></html>`}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store'}})}
function html(s,status=200){return new Response(s,{status,headers:{'content-type':'text/html;charset=UTF-8','cache-control':'no-store'}})}
function normPhone(v){return String(v??'').replace(/\D/g,'')}
function makeToken(){return crypto.randomUUID().replace(/-/g,'')+crypto.randomUUID().replace(/-/g,'')}

export default {async fetch(request,env){const url=new URL(request.url);
if(url.pathname==='/admin/upload')return html(ADMIN_PAGE);
if(url.pathname.startsWith('/c/')){const token=decodeURIComponent(url.pathname.slice(3));if(!token)return html(notFoundHtml(),404);let c=null;const direct=await env.BALANCES.get(CUSTOMER_PREFIX+token,'json');if(direct)c=direct;if(!c){const raw=await env.BALANCES.get(DATA_KEY);if(raw)try{const cs=JSON.parse(raw);c=cs.find(x=>x.token===token)||null;if(c)await env.BALANCES.put(CUSTOMER_PREFIX+token,JSON.stringify(c));}catch{}}if(!c)return html(notFoundHtml(),404);const exchangeRate=Number(await env.BALANCES.get(EXCHANGE_KEY))||DEFAULT_EXCHANGE_RATE;return html(customerHtml(c,exchangeRate))}
if(url.pathname==='/api/rate'&&request.method==='GET'){const rate=Number(await env.BALANCES.get(EXCHANGE_KEY))||DEFAULT_EXCHANGE_RATE;return json({ok:true,rate})}
if(url.pathname==='/api/rate'&&request.method==='POST'){if(request.headers.get('x-admin-token')!==env.ADMIN_TEST_TOKEN)return json({ok:false,error:'Unauthorized'},401);let body;try{body=await request.json()}catch{return json({ok:false,error:'Invalid JSON'},400)}const rate=Number(body.rate);if(!Number.isFinite(rate)||rate<=0)return json({ok:false,error:'Invalid exchange rate.'},400);await env.BALANCES.put(EXCHANGE_KEY,String(rate));return json({ok:true,rate})}
if(url.pathname==='/api/private/'||url.pathname.startsWith('/api/private/')){const token=decodeURIComponent(url.pathname.slice('/api/private/'.length));const c=await env.BALANCES.get(CUSTOMER_PREFIX+token,'json');return c?json({ok:true,customer:c}):json({ok:false,error:'Private link not found.'},404)}
if(url.pathname==='/api/upload'&&request.method==='POST'){if(request.headers.get('x-admin-token')!==env.ADMIN_TEST_TOKEN)return json({ok:false,error:'Unauthorized'},401);let body;try{body=await request.json()}catch{return json({ok:false,error:'Invalid JSON'},400)}if(!Array.isArray(body.clients)||!body.clients.length)return json({ok:false,error:'No customers received.'},400);let old=[];let raw=await env.BALANCES.get(DATA_KEY);if(!raw)raw=await env.BALANCES.get("clients");if(raw)try{old=JSON.parse(raw)}catch{}const oldMap=new Map(old.filter(c=>c&&c.phone).map(c=>[normPhone(c.phone),c]));const incoming=new Map(body.clients.filter(c=>c&&c.phone).map(c=>[normPhone(c.phone),c]));for(const c of old){if(!c.token)c.token=makeToken();const n=incoming.get(normPhone(c.phone));if(n){c.name=n.name;c.phone=n.phone;c.remaining=Number(n.remaining)||0}else{c.remaining=0}await env.BALANCES.put(CUSTOMER_PREFIX+c.token,JSON.stringify(c))}for(const n of body.clients){const p=normPhone(n.phone);if(!p||oldMap.has(p))continue;const c={name:n.name,phone:n.phone,remaining:Number(n.remaining)||0,token:makeToken()};old.push(c);oldMap.set(p,c);await env.BALANCES.put(CUSTOMER_PREFIX+c.token,JSON.stringify(c))}await env.BALANCES.put(DATA_KEY,JSON.stringify(old));await env.BALANCES.put(META_KEY,JSON.stringify({updatedAt:new Date().toISOString(),count:old.length}));return json({ok:true,count:body.clients.length,customers:old.map(c=>({name:c.name,phone:c.phone,remaining:c.remaining,token:c.token}))})}
return Response.redirect(new URL('/admin/upload',request.url).toString(),302)}};
